// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgwVvIEYvEpib6kl43HBWGXNwzFIjC_Q',
    appId: '1:889257564514:web:ea0e0fc525a415e635743b',
    messagingSenderId: '889257564514',
    projectId: 'bike-rental-project-3d4e6',
    authDomain: 'bike-rental-project-3d4e6.firebaseapp.com',
    storageBucket: 'bike-rental-project-3d4e6.firebasestorage.app',
    measurementId: 'G-XVTY2VM4GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYoG7R7hqfgnrHsDcBMQp5m3u3Xv4jzVg',
    appId: '1:889257564514:android:534206881e31cd9535743b',
    messagingSenderId: '889257564514',
    projectId: 'bike-rental-project-3d4e6',
    storageBucket: 'bike-rental-project-3d4e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ZBBlG_My4-x9O8NylRQFu86p4yYwMSo',
    appId: '1:889257564514:ios:55c0e8ccd617e2ac35743b',
    messagingSenderId: '889257564514',
    projectId: 'bike-rental-project-3d4e6',
    storageBucket: 'bike-rental-project-3d4e6.firebasestorage.app',
    iosBundleId: 'com.example.bikeRentalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ZBBlG_My4-x9O8NylRQFu86p4yYwMSo',
    appId: '1:889257564514:ios:55c0e8ccd617e2ac35743b',
    messagingSenderId: '889257564514',
    projectId: 'bike-rental-project-3d4e6',
    storageBucket: 'bike-rental-project-3d4e6.firebasestorage.app',
    iosBundleId: 'com.example.bikeRentalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJgwVvIEYvEpib6kl43HBWGXNwzFIjC_Q',
    appId: '1:889257564514:web:a7107d515d8e408135743b',
    messagingSenderId: '889257564514',
    projectId: 'bike-rental-project-3d4e6',
    authDomain: 'bike-rental-project-3d4e6.firebaseapp.com',
    storageBucket: 'bike-rental-project-3d4e6.firebasestorage.app',
    measurementId: 'G-3935XYNQLT',
  );
}
